# Generated by Django 3.2.12 on 2022-06-20 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='items',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('descriptions', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='sections',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('descriptions', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='modifiers',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('descriptions', models.CharField(max_length=200)),
                ('items_id', models.ForeignKey(db_column='items_id', on_delete=django.db.models.deletion.CASCADE, to='hotelmenu.items')),
            ],
        ),
        migrations.AddField(
            model_name='items',
            name='section_id',
            field=models.ForeignKey(db_column='section_id', on_delete=django.db.models.deletion.CASCADE, to='hotelmenu.sections'),
        ),
    ]
